// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBmJKY-YfaiovSlr1Azuek_2ntvnR0unHY',
    appId: '1:877930310747:web:d81e9b5a2cb35e9815237e',
    messagingSenderId: '877930310747',
    projectId: 'notes-app-task-67382',
    authDomain: 'notes-app-task-67382.firebaseapp.com',
    storageBucket: 'notes-app-task-67382.appspot.com',
    measurementId: 'G-NY7V5B8CQ5',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCaCjy1AqD2U4UThUWnK1SYZ5uloHD0WYE',
    appId: '1:877930310747:android:1bef04df18b462d815237e',
    messagingSenderId: '877930310747',
    projectId: 'notes-app-task-67382',
    storageBucket: 'notes-app-task-67382.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBA_rH74DmQIie8Ou4GOhwqT-iO-br9-NI',
    appId: '1:877930310747:ios:5835956096cc1cae15237e',
    messagingSenderId: '877930310747',
    projectId: 'notes-app-task-67382',
    storageBucket: 'notes-app-task-67382.appspot.com',
    iosBundleId: 'com.example.notesAppTask',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBA_rH74DmQIie8Ou4GOhwqT-iO-br9-NI',
    appId: '1:877930310747:ios:522f92087ca7527b15237e',
    messagingSenderId: '877930310747',
    projectId: 'notes-app-task-67382',
    storageBucket: 'notes-app-task-67382.appspot.com',
    iosBundleId: 'com.example.notesAppTask.RunnerTests',
  );
}
